### ISSUE TITLE
plunker demo not working.

### ISSUE THREAD

**Issue by eadolf** [dbaq/angularjs-google-directions#1]
I wasn't having any success with the current or previous demo version. No data was displaying.

**Comment by dbaq** [comment]
hey @eadolf, 

the demo here is working fine: http://embed.plnkr.co/sfe1hrZcKsYeKRIMMUBJ/preview

**Comment by eadolf** [comment]
![screen shot 2015-02-18 at 4 58 02 pm](https://cloud.githubusercontent.com/assets/8332936/6257701/7f78bde4-b790-11e4-94aa-5d241881c9a4.png)

I was expecting a map, but this is what I'm seeing. If this is correct, than ok.

**Comment by dbaq** [comment]
Oh no sorry, this is correct. This plnkr is just an example of what the plugin returns.

**Comment by eadolf** [comment]
sorry for misunderstanding -- thanks for your quick replies.
