### ISSUE TITLE
Offline issue

### ISSUE THREAD

**Issue by utkuturunc** [dbaq/angularjs-google-directions#5]
Using this plugin offline causes google is not defined error. This may cause problems especially on mobile apps that were launched without an internet connection. Of course internet is essential for google maps but the error should be handled anyway.

**Comment by dbaq** [comment]
It's true. That's one of the main reason why I moved the google directions code on the server side for my project.

But it should be possible to inject the google maps library if it failed the first time. A good start will be to look at other angularjs libraries using google maps library.
